export const ALOFOKE_CHANNEL_ID = "UCvDvBAOuJIHKWK59duvM0JQ";
export const SINFILTRO_CHANNEL_ID = "UCPA3VgcdfxUIJMJ2Nu5loYw";
export const ESTONOESRADIO_CHANNEL_ID = "UC7VS4RyzyvPKYHZc-uFH7mQ";
export const ELOPENMIC_CHANNEL_ID = "UCiyib8l16c1MrRa1CJcdxlw";
export const LAALDEA_CHANNEL_ID = "UCsHmijE0NKFXMnebS2zeImQ";
export const ALOFOKEPODCAST_CHANNEL_ID = "UC9MntPPfG6L4Vj18ZJyfpqw";
export const ALOFOKENETWORK_CHANNEL_ID = "UC1QMzlSrgn8gCu1kCUOj4zQ";

export const CHANNELS_ID = [
  ALOFOKE_CHANNEL_ID,
  SINFILTRO_CHANNEL_ID,
  ESTONOESRADIO_CHANNEL_ID,
  ELOPENMIC_CHANNEL_ID,
  LAALDEA_CHANNEL_ID,
  ALOFOKEPODCAST_CHANNEL_ID,
  ALOFOKENETWORK_CHANNEL_ID,
];
